import type { AiContext, ExamStrategy, RecoveryCoach, RescueInput, StudyInsights, StudyStrategy, TopicContext, WhyExplanation } from "./ai.types.js";

export function fallbackStrategy(topic: TopicContext, minutes: number): StudyStrategy {
  const recommendedStrategy = topic.preparation === "Not Started" ? "Concepts" : topic.difficulty === "Hard" || topic.difficultFeedbackCount ? "Concepts + Practice" : topic.preparation === "Revision Needed" ? "Active Recall" : "Practice";
  return { subject: topic.subject, topic: topic.topic, recommendedStrategy, reason: `${topic.topic} is ${topic.difficulty.toLowerCase()} and currently marked ${topic.preparation.toLowerCase()}.`, nextAction: recommendedStrategy === "Concepts" ? "Review the core idea, then write a short explanation from memory." : "Work through one focused example and check the steps you found difficult.", suggestedMinutes: minutes };
}
export function fallbackWhy(session: { why: string; topic: string; strategy: string; priorityScore: number }): WhyExplanation { return { headline: `${session.topic} is a current priority`, reason: session.why, focusTip: `Use ${session.strategy.toLowerCase()} and focus on one clear outcome for this session.` }; }
export function fallbackCoach(result: RescueInput): RecoveryCoach { return { summary: `${result.movedSessions} sessions were placed into the rebuilt plan, recovering ${result.recoveredMinutes} minutes.`, priority: result.overloadedTopics[0] ? `Protect time for ${result.overloadedTopics[0]}.` : "Start with the highest-priority session in the rebuilt plan.", nextStep: "Review the updated plan and begin the next realistic session.", warning: result.remainingUnscheduledMinutes > 0 ? `${result.remainingUnscheduledMinutes} minutes could not fit within your current availability.` : null }; }
export function fallbackExam(context: AiContext): ExamStrategy { const days = context.exam?.daysRemaining ?? 0; const risk = context.readiness < 40 || days <= 7 ? "high" : context.readiness < 70 ? "medium" : "low"; return { summary: `You have ${days} days remaining with ${context.readiness}% measured readiness.`, topPriorities: context.priorityTopics.slice(0, 3).map((topic) => `${topic.subject}: ${topic.topic}`), dailyApproach: `Use your ${context.availability.preferredSessionMinutes}-minute session rhythm and begin with the highest-priority topic.`, revisionAdvice: "Revisit weak topics with active recall, then verify understanding with practice.", risk }; }
export function fallbackInsights(context: AiContext): StudyInsights { const observations: StudyInsights["observations"] = []; if (context.strongAreas[0]) observations.push({ title: "Current strength", detail: `${context.strongAreas[0].topic} has your strongest current progress signal.`, type: "strength" }); if (context.progress.feedback.difficult) observations.push({ title: "Difficulty signal", detail: `${context.progress.feedback.difficult} session feedback entries were marked difficult.`, type: "warning" }); if (context.weakAreas[0]) observations.push({ title: "Best opportunity", detail: `${context.weakAreas[0].topic} is a useful next area for focused work.`, type: "opportunity" }); return { summary: `Your current completion rate is ${context.progress.completionRate}% with a ${context.progress.streak}-day streak.`, observations: observations.slice(0, 3), actions: context.priorityTopics.slice(0, 2).map((topic) => `Schedule focused work on ${topic.topic}.`) }; }
